"""added confirmation to user table

Revision ID: 48b03a45ac97
Revises: 5b969e1f35e0
Create Date: 2020-11-04 22:20:13.832829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b03a45ac97'
down_revision = '5b969e1f35e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_at')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
